fixtures:
  repositories:
    windows_env: "git@github.com:badgerious/puppet-windows-env.git"
    powershell: "git@github.com:joshcooper/puppetlabs-powershell.git"
  symlinks:
    windows_java: "#{source_dir}"
