language: ruby
script: "bundle exec rake spec SPEC_OPTS='--format documentation'"
rvm:
  - 1.9.3
  - 2.0.0
env:
  - PUPPET_GEM_VERSION="~> 3.0.0"
  - PUPPET_GEM_VERSION="~> 3.2.0"
  - PUPPET_GEM_VERSION="~> 3.3.0"
  - PUPPET_GEM_VERSION="~> 3.4.0"
branches:
  only:
    - master
matrix:
  exclude:
    - rvm: 1.9.3
      env: PUPPET_GEM_VERSION="~> 3.0.0"
    - rvm: 2.0.0
      env: PUPPET_GEM_VERSION="~> 3.0.0"
    - rvm: 1.9.3
      env: PUPPET_GEM_VERSION="~> 3.2.0"
    - rvm: 2.0.0
      env: PUPPET_GEM_VERSION="~> 3.2.0"
    - rvm: 1.9.3
      env: PUPPET_GEM_VERSION="~> 3.3.0"
    - rvm: 2.0.0
      env: PUPPET_GEM_VERSION="~> 3.3.0"
    - rvm: 1.9.3
      env: PUPPET_GEM_VERSION="~> 3.4.0"
    - rvm: 2.0.0
      env: PUPPET_GEM_VERSION="~> 3.4.0"
notifications:
  email: false
